# Site Settings
title: Jekyll Test
author: CXXL
email: prod.cxxl@gmail.com
description: >
  A test to getting started with Jekyll.
baseurl: '/Jekyll-Test'
url: 'https://prod-cxxl.github.io'
twitter_username: Prod. CXXL
github_username: Prod. CXXL
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
plugins: 
  - jekyll-feed
feed:
  icon: /images/LogoBG.png
  logo: /images/LogoFull.png